// Generated by tools/embed_kws_model.py. Do not edit.
#ifndef XIAOV_GENERATED_XV_KWS_MODEL_H
#define XIAOV_GENERATED_XV_KWS_MODEL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t xv_kws_model_data[];
extern const size_t xv_kws_model_size;
extern const char xv_kws_model_sha256[];
extern const char xv_kws_model_license_id[];
extern const char xv_kws_model_license_source[];
extern const size_t xv_kws_model_input_elements;
extern const float xv_kws_model_input_scale;
extern const int32_t xv_kws_model_input_zero_point;
extern const size_t xv_kws_model_output_elements;
extern const float xv_kws_model_output_scale;
extern const int32_t xv_kws_model_output_zero_point;
extern const uint16_t xv_kws_model_wake_class_indices[];
extern const char *const xv_kws_model_wake_class_labels[];
extern const size_t xv_kws_model_wake_class_count;

#ifdef __cplusplus
}
#endif

#endif
